name: composite
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ontargetcomputing/github-actions-shared/.github/workflows/composite@main
        with: 
          name: OctoCat
      - name: foo
        run: |
          echo foo