name: composite
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ontargetcomputing/github-actions-shared/.github/actions/composite@main
        id: foobar
        with: 
          name: OctoCat
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID_032802432428_DEV }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_032802432428_DEV }}
      - name: Print it
        run: |
          echo random-number ${{ steps.foobar.outputs }}
      - name: foo
        run: |
          echo foo
      - name: Try it here
        run: |
          aws s3 ls   